[package]
name = "scim2-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
dropshot.workspace = true
http.workspace = true
schemars.workspace = true
serde_json.workspace = true
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true
uuid.workspace = true
chrono.workspace = true
