#
# Configuration for GitHub-based CI, based on the stock GitHub Rust config.
#
name: Rust

on:
  push:
    branches:
      - main
      - 'rel/**'
  pull_request: {}

jobs:
  check-style:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ github.event.pull_request.head.sha }} # see omicron#4461
    - name: Report cargo version
      run: cargo --version
    - name: Report rustfmt version
      run: cargo fmt -- --version
    - name: Check style
      run: cargo fmt -- --check

  # Note that `cargo clippy` includes `cargo check, so this ends up checking all
  # of our (default) code.
  clippy-lint:
    runs-on: ubuntu-22.04
    env:
      CARGO_INCREMENTAL: 0
    steps:
    # This repo is unstable and unnecessary: https://github.com/microsoft/linux-package-repositories/issues/34
    - name: Disable packages.microsoft.com repo
      run: sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ github.event.pull_request.head.sha }} # see omicron#4461
    - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
      if: ${{ github.ref != 'refs/heads/main' }}
    - name: Report cargo version
      run: cargo --version
    - name: Report Clippy version
      run: cargo clippy -- --version
    - name: Run Clippy Lints
      run: cargo clippy --all-targets --workspace -- --deny warnings 
